package io.pleo.antaeus.core.exceptions

class NetworkException : Exception("A network error happened please try again.")
